### ISSUE TITLE
ST207 Missing Display Representation

### ISSUE THREAD

**Issue by ludwich66** [webspiderteam/Bluetooth-DMM-For-Windows#33]
Displayelement is missing:
https://github.com/ludwich66/Bluetooth-DMM/raw/main/Display_(3)_720.png
REL
PEAKHOLD

Video from Krzysztof
Min 25:40 
https://www.youtube.com/watch?v=Wwh6yD25Z7Q

Hi Engin, please help Krzysztof (and me) 
i don't find LOG RAW Datas File 
I serched in d Inst Path and App Data path (?) - Blind Men

Grüße Ludwich

**Comment by webspiderteam** [comment]
Peek Hold is working. Peek translated as zerkac as seen on display and hold is showing as red numbers. But yes rel is missing because ı have no data about it. I even don't know it has rel function. I never seen it on other videos. İf you know or your device has it i can add. İt's only shows up in capacitance mode

**Comment by ludwich66** [comment]
Oh, I must have misunderstood. Thank you for your prompt reply.

?? Where can I find the RAW data when the installation is complete?

L

**Comment by webspiderteam** [comment]
Raw data is still under app directory with filename date-time of record dot log but not sure about raw data function is enabled by default. You have to check it in settings
