### ISSUE TITLE
Cannot finf DMM service

### ISSUE THREAD

**Issue by kris0725pl** [webspiderteam/Bluetooth-DMM-For-Windows#45]
i have problem to connect multimeter over bluetooth. I got issue Cannot find DMM service....?

**Comment by webspiderteam** [comment]
can you sen me logs under app dir?

**Comment by kris0725pl** [comment]
Some time works ok...some time have problem with bluetooth connection. ON APP  i see connected but i got error cannot find dmm service. wait for 5min i upload video when i got this error :)

**Comment by kris0725pl** [comment]
see this error
https://youtu.be/6DVPgtAJghc?t=3290

**Comment by webspiderteam** [comment]
> PS: i dont see in app options log checkbox :)

it should automatically log when there is error. 

BTW did you try with older version ? is it latest version that you are using?

**Comment by webspiderteam** [comment]
I watched the video and there can be several things. first of all while trying to reconnect the system look like lacked and slowed down this can caused by dll errors that can effect app. Also there were always a bluetooth problems with windows coommunucation. sometimes bluetooth adapter can get stuct and gives errors as you know when you try first version of app that happened. disabling and enabling bluetooth adapter can solve this issue. Also I saw that you have 2 device added with same mac address I dont think this can cause any problem but you can try to remove both from app setting may be there could be an issue. BTW you are already logging raw data you can disable it from advanced settings tab (First option in list).
Looks like Cannot find service error given because bluetooth connection was already made but when you close the app DMM didnt realize disconnected. Sometimes Happens with my device too. you should wait until bluetooth symbol lstart to blimk on multimeter screen or power of and on again. But in your situation the mosy possible reason is system error because also arduino ide also gived an error and as you can see in video bluetooth connection symbol even stucking. there is no reason to stuck blinking because app does nothing while its blinking.

**Comment by kris0725pl** [comment]
Ok, i undesstand :) i try next time your hints. Of course app works great and is the Best :) regards.
Close this issue :)

**Comment by webspiderteam** [comment]
> Of course app works great and is the Best :) regards.

of course there could be an issue but I couldnt see any evidence that caused by app. because app was working. but if these are not solves the issue I need to findout why its happened and looks like it woul be hard to find because there is no evidence.  



> Close this issue :)

I will close when I'm sure that there is no issue with my code ;) so i will wait for your result :)

**Comment by kris0725pl** [comment]
Ok..works great. One instance bluetooth works great. It is my fault ,) close.
