### ISSUE TITLE
Missing Donate link on the repo

### ISSUE THREAD

**Issue by kosma** [webspiderteam/Bluetooth-DMM-For-Windows#48]
I wanted to send you ten bucks as a thank you for this piece of software but there is no Donate link. Please fix. :D

**Comment by webspiderteam** [comment]
Thank you for your wishes to support me and kindness :) but there is two reason that I didn't put donation link. First one is, I didn't make this project to make money. Just wanted to help people like me that wanted to use their dmm on pc and I like to watch repairing videos. if I see the app on videos It mekes me happy. 
Second reason is paypal or buymecofee does not works in Turkey maybe there is another ways but I didn't made a research because of the first reason.
